# Generated by Django 3.1.4 on 2020-12-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='verify',
        ),
    ]
