# Generated by Django 3.1.4 on 2020-12-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_userprofileinfo_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(default='hello', max_length=122),
        ),
    ]
