# Generated by Django 3.1.4 on 2020-12-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_userprofileinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='username',
        ),
    ]
