# Generated by Django 3.1.4 on 2020-12-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_userprofileinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
    ]
