# Generated by Django 3.1.4 on 2020-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_courseforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseforms',
            name='title',
            field=models.CharField(max_length=122),
        ),
    ]
