# Generated by Django 3.1.4 on 2020-12-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_auto_20201214_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseforms',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.instructor'),
        ),
    ]
